server:
  port: 8082

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.16.0.198:3308/poetry_game?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT&allowMultiQueries=true
    username: changzhi
    password: changzhi6699
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

wechat:
  appid:  'wx831e23aaf0249b23'
  appSecret: 'e53c89818ee93568b8f444ba33ca31d1'
mybatis-plus:
  #  type-aliases-package: com.example.pojo  #??
  mapper-locations: classpath:/mybatis/*.xml # xml??

